/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.juego.taken;

/**
 *
 * @author Haciel
 */
public class Disposiciones extends javax.swing.JFrame {
    Taken t = new Taken();
    /**
     * Creates new form Disposiciones
     */
    public Disposiciones() {
        initComponents();
        jTextField1.setText(t.Horizontal[0]);
        jTextField2.setText(t.Horizontal[1]);
        jTextField3.setText(t.Horizontal[2]);
        jTextField4.setText(t.Horizontal[3]);
        jTextField5.setText(t.Horizontal[4]);
        jTextField6.setText(t.Horizontal[5]);
        jTextField7.setText(t.Horizontal[6]);
        jTextField8.setText(t.Horizontal[7]);
        jTextField9.setText(t.Horizontal[8]);
        jTextField10.setText(t.Horizontal[9]);
        jTextField11.setText(t.Horizontal[10]);
        jTextField12.setText(t.Horizontal[11]);
        jTextField13.setText(t.Horizontal[12]);
        jTextField14.setText(t.Horizontal[13]);
        jTextField15.setText(t.Horizontal[14]);
        jTextField16.setText(t.Horizontal[15]);
        jTextField17.setText("Horizontal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField17 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField16.setEditable(false);
        jTextField16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField14.setEditable(false);
        jTextField14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField15.setEditable(false);
        jTextField15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Dispocisiones");

        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField17.setEditable(false);

        jLabel2.setText("Estas son las diferentes formas en que puedes ganar.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jTextField17))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jButton3)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(66, 66, 66)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(65, 65, 65)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //accion derecha
        String aux = jTextField17.getText();
        if("Horizontal".equals(aux)){
            jTextField1.setText(t.Espiral[0]);
            jTextField2.setText(t.Espiral[1]);
            jTextField3.setText(t.Espiral[2]);
            jTextField4.setText(t.Espiral[3]);
            jTextField5.setText(t.Espiral[4]);
            jTextField6.setText(t.Espiral[5]);
            jTextField7.setText(t.Espiral[6]);
            jTextField8.setText(t.Espiral[7]);
            jTextField9.setText(t.Espiral[8]);
            jTextField10.setText(t.Espiral[9]);
            jTextField11.setText(t.Espiral[10]);
            jTextField12.setText(t.Espiral[11]);
            jTextField13.setText(t.Espiral[12]);
            jTextField14.setText(t.Espiral[13]);
            jTextField15.setText(t.Espiral[14]);
            jTextField16.setText(t.Espiral[15]);
            jTextField17.setText("Espiral");
        }
        if("Espiral".equals(aux)){
            jTextField1.setText(t.Imposible[0]);
            jTextField2.setText(t.Imposible[1]);
            jTextField3.setText(t.Imposible[2]);
            jTextField4.setText(t.Imposible[3]);
            jTextField5.setText(t.Imposible[4]);
            jTextField6.setText(t.Imposible[5]);
            jTextField7.setText(t.Imposible[6]);
            jTextField8.setText(t.Imposible[7]);
            jTextField9.setText(t.Imposible[8]);
            jTextField10.setText(t.Imposible[9]);
            jTextField11.setText(t.Imposible[10]);
            jTextField12.setText(t.Imposible[11]);
            jTextField13.setText(t.Imposible[12]);
            jTextField14.setText(t.Imposible[13]);
            jTextField15.setText(t.Imposible[14]);
            jTextField16.setText(t.Imposible[15]);
            jTextField17.setText("Imposible");
        }
        if("Imposible".equals(aux)){
            jTextField1.setText(t.Periferico[0]);
            jTextField2.setText(t.Periferico[1]);
            jTextField3.setText(t.Periferico[2]);
            jTextField4.setText(t.Periferico[3]);
            jTextField5.setText(t.Periferico[4]);
            jTextField6.setText(t.Periferico[5]);
            jTextField7.setText(t.Periferico[6]);
            jTextField8.setText(t.Periferico[7]);
            jTextField9.setText(t.Periferico[8]);
            jTextField10.setText(t.Periferico[9]);
            jTextField11.setText(t.Periferico[10]);
            jTextField12.setText(t.Periferico[11]);
            jTextField13.setText(t.Periferico[12]);
            jTextField14.setText(t.Periferico[13]);
            jTextField15.setText(t.Periferico[14]);
            jTextField16.setText(t.Periferico[15]);
            jTextField17.setText("Periferico");
        }
        if("Periferico".equals(aux)){
            jTextField1.setText(t.Vertical[0]);
            jTextField2.setText(t.Vertical[1]);
            jTextField3.setText(t.Vertical[2]);
            jTextField4.setText(t.Vertical[3]);
            jTextField5.setText(t.Vertical[4]);
            jTextField6.setText(t.Vertical[5]);
            jTextField7.setText(t.Vertical[6]);
            jTextField8.setText(t.Vertical[7]);
            jTextField9.setText(t.Vertical[8]);
            jTextField10.setText(t.Vertical[9]);
            jTextField11.setText(t.Vertical[10]);
            jTextField12.setText(t.Vertical[11]);
            jTextField13.setText(t.Vertical[12]);
            jTextField14.setText(t.Vertical[13]);
            jTextField15.setText(t.Vertical[14]);
            jTextField16.setText(t.Vertical[15]);
            jTextField17.setText("Vertical");
        }
        if("Vertical".equals(aux)){
            jTextField1.setText(t.Horizontal[0]);
            jTextField2.setText(t.Horizontal[1]);
            jTextField3.setText(t.Horizontal[2]);
            jTextField4.setText(t.Horizontal[3]);
            jTextField5.setText(t.Horizontal[4]);
            jTextField6.setText(t.Horizontal[5]);
            jTextField7.setText(t.Horizontal[6]);
            jTextField8.setText(t.Horizontal[7]);
            jTextField9.setText(t.Horizontal[8]);
            jTextField10.setText(t.Horizontal[9]);
            jTextField11.setText(t.Horizontal[10]);
            jTextField12.setText(t.Horizontal[11]);
            jTextField13.setText(t.Horizontal[12]);
            jTextField14.setText(t.Horizontal[13]);
            jTextField15.setText(t.Horizontal[14]);
            jTextField16.setText(t.Horizontal[15]);
            jTextField17.setText("Horizontal");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //accion izquierda
        String aux = jTextField17.getText();
        
        if("Horizontal".equals(aux)){
            jTextField1.setText(t.Vertical[0]);
            jTextField2.setText(t.Vertical[1]);
            jTextField3.setText(t.Vertical[2]);
            jTextField4.setText(t.Vertical[3]);
            jTextField5.setText(t.Vertical[4]);
            jTextField6.setText(t.Vertical[5]);
            jTextField7.setText(t.Vertical[6]);
            jTextField8.setText(t.Vertical[7]);
            jTextField9.setText(t.Vertical[8]);
            jTextField10.setText(t.Vertical[9]);
            jTextField11.setText(t.Vertical[10]);
            jTextField12.setText(t.Vertical[11]);
            jTextField13.setText(t.Vertical[12]);
            jTextField14.setText(t.Vertical[13]);
            jTextField15.setText(t.Vertical[14]);
            jTextField16.setText(t.Vertical[15]);
            jTextField17.setText("Vertical");
        }
        if("Vertical".equals(aux)){
            jTextField1.setText(t.Periferico[0]);
            jTextField2.setText(t.Periferico[1]);
            jTextField3.setText(t.Periferico[2]);
            jTextField4.setText(t.Periferico[3]);
            jTextField5.setText(t.Periferico[4]);
            jTextField6.setText(t.Periferico[5]);
            jTextField7.setText(t.Periferico[6]);
            jTextField8.setText(t.Periferico[7]);
            jTextField9.setText(t.Periferico[8]);
            jTextField10.setText(t.Periferico[9]);
            jTextField11.setText(t.Periferico[10]);
            jTextField12.setText(t.Periferico[11]);
            jTextField13.setText(t.Periferico[12]);
            jTextField14.setText(t.Periferico[13]);
            jTextField15.setText(t.Periferico[14]);
            jTextField16.setText(t.Periferico[15]);
            jTextField17.setText("Periferico");
        }
        if("Periferico".equals(aux)){
            jTextField1.setText(t.Imposible[0]);
            jTextField2.setText(t.Imposible[1]);
            jTextField3.setText(t.Imposible[2]);
            jTextField4.setText(t.Imposible[3]);
            jTextField5.setText(t.Imposible[4]);
            jTextField6.setText(t.Imposible[5]);
            jTextField7.setText(t.Imposible[6]);
            jTextField8.setText(t.Imposible[7]);
            jTextField9.setText(t.Imposible[8]);
            jTextField10.setText(t.Imposible[9]);
            jTextField11.setText(t.Imposible[10]);
            jTextField12.setText(t.Imposible[11]);
            jTextField13.setText(t.Imposible[12]);
            jTextField14.setText(t.Imposible[13]);
            jTextField15.setText(t.Imposible[14]);
            jTextField16.setText(t.Imposible[15]);
            jTextField17.setText("Imposible");
        }
        if("Imposible".equals(aux)){
            jTextField1.setText(t.Espiral[0]);
            jTextField2.setText(t.Espiral[1]);
            jTextField3.setText(t.Espiral[2]);
            jTextField4.setText(t.Espiral[3]);
            jTextField5.setText(t.Espiral[4]);
            jTextField6.setText(t.Espiral[5]);
            jTextField7.setText(t.Espiral[6]);
            jTextField8.setText(t.Espiral[7]);
            jTextField9.setText(t.Espiral[8]);
            jTextField10.setText(t.Espiral[9]);
            jTextField11.setText(t.Espiral[10]);
            jTextField12.setText(t.Espiral[11]);
            jTextField13.setText(t.Espiral[12]);
            jTextField14.setText(t.Espiral[13]);
            jTextField15.setText(t.Espiral[14]);
            jTextField16.setText(t.Espiral[15]);
            jTextField17.setText("Espiral");
        }
        if("Espiral".equals(aux)){
            jTextField1.setText(t.Horizontal[0]);
            jTextField2.setText(t.Horizontal[1]);
            jTextField3.setText(t.Horizontal[2]);
            jTextField4.setText(t.Horizontal[3]);
            jTextField5.setText(t.Horizontal[4]);
            jTextField6.setText(t.Horizontal[5]);
            jTextField7.setText(t.Horizontal[6]);
            jTextField8.setText(t.Horizontal[7]);
            jTextField9.setText(t.Horizontal[8]);
            jTextField10.setText(t.Horizontal[9]);
            jTextField11.setText(t.Horizontal[10]);
            jTextField12.setText(t.Horizontal[11]);
            jTextField13.setText(t.Horizontal[12]);
            jTextField14.setText(t.Horizontal[13]);
            jTextField15.setText(t.Horizontal[14]);
            jTextField16.setText(t.Horizontal[15]);
            jTextField17.setText("Horizontal");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Disposiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Disposiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Disposiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Disposiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Disposiciones().setVisible(true);
            }
            int opc=1;
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
