/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.juego.taken;

/**
 *
 * @author Haciel
 */
public class Principal extends javax.swing.JFrame {
    Taken t = new Taken();
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
       jButton1.setText(t.tablero.get(0));
       jButton2.setText(t.tablero.get(1));
       jButton3.setText(t.tablero.get(2));
       jButton4.setText(t.tablero.get(3));
       jButton5.setText(t.tablero.get(4));
       jButton6.setText(t.tablero.get(5));
       jButton7.setText(t.tablero.get(6));
       jButton8.setText(t.tablero.get(7));
       jButton9.setText(t.tablero.get(8));
       jButton10.setText(t.tablero.get(9));
       jButton11.setText(t.tablero.get(10));
       jButton12.setText(t.tablero.get(11));
       jButton13.setText(t.tablero.get(12));
       jButton14.setText(t.tablero.get(13));
       jButton15.setText(t.tablero.get(14));
       jButton16.setText(t.tablero.get(15));
       jTextField17.setText("Juego listo para comenzar.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jTextField17 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Taken");

        jButton17.setText("Reinicio");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Disposiciones");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jTextField17.setEditable(false);

        jTextField19.setEditable(false);
        jTextField19.setText("0");

        jLabel3.setText("Movimientos:");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jButton17)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton18)
                                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(jButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        Disposiciones d = new Disposiciones();
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       t.reiniciar();
       jButton1.setText(t.tablero.get(0));
       jButton2.setText(t.tablero.get(1));
       jButton3.setText(t.tablero.get(2));
       jButton4.setText(t.tablero.get(3));
       jButton5.setText(t.tablero.get(4));
       jButton6.setText(t.tablero.get(5));
       jButton7.setText(t.tablero.get(6));
       jButton8.setText(t.tablero.get(7));
       jButton9.setText(t.tablero.get(8));
       jButton10.setText(t.tablero.get(9));
       jButton11.setText(t.tablero.get(10));
       jButton12.setText(t.tablero.get(11));
       jButton13.setText(t.tablero.get(12));
       jButton14.setText(t.tablero.get(13));
       jButton15.setText(t.tablero.get(14));
       jButton16.setText(t.tablero.get(15));
       jTextField17.setText("");
       jTextField19.setText(String.valueOf(t.obtenerMovimientos()));
       jTextField17.setText("El tablero se ha reiniciado.");
       
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
            jButton8.setEnabled(true);
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
            jButton11.setEnabled(true);
            jButton12.setEnabled(true);
            jButton13.setEnabled(true);
            jButton14.setEnabled(true);
            jButton15.setEnabled(true);
            jButton16.setEnabled(true);
       
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton15.getText())){
            a = Integer.parseInt(jButton15.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton14.getText())){
            a = Integer.parseInt(jButton14.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton13.getText())){
            a = Integer.parseInt(jButton13.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton12.getText())){
            a = Integer.parseInt(jButton12.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton11.getText())){
            a = Integer.parseInt(jButton11.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton10.getText())){
            a = Integer.parseInt(jButton10.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton9.getText())){
            a = Integer.parseInt(jButton9.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton8.getText())){
            a = Integer.parseInt(jButton8.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton7.getText())){
            a = Integer.parseInt(jButton7.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton6.getText())){
            a = Integer.parseInt(jButton6.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton5.getText())){
            a = Integer.parseInt(jButton5.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton4.getText())){
            a = Integer.parseInt(jButton4.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton3.getText())){
            a = Integer.parseInt(jButton3.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton2.getText())){
            a = Integer.parseInt(jButton2.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton1.getText())){
            a = Integer.parseInt(jButton1.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        int a = 16;
        String r;
        if(!"".equals(jButton16.getText())){
            a = Integer.parseInt(jButton16.getText());
        }
        if(a <= 15){
            r = t.moverTecla(a);
        }
        else{
            r = "No es posible mover la tecla.";
        }

        jButton1.setText(t.tablero.get(0));
        jButton2.setText(t.tablero.get(1));
        jButton3.setText(t.tablero.get(2));
        jButton4.setText(t.tablero.get(3));
        jButton5.setText(t.tablero.get(4));
        jButton6.setText(t.tablero.get(5));
        jButton7.setText(t.tablero.get(6));
        jButton8.setText(t.tablero.get(7));
        jButton9.setText(t.tablero.get(8));
        jButton10.setText(t.tablero.get(9));
        jButton11.setText(t.tablero.get(10));
        jButton12.setText(t.tablero.get(11));
        jButton13.setText(t.tablero.get(12));
        jButton14.setText(t.tablero.get(13));
        jButton15.setText(t.tablero.get(14));
        jButton16.setText(t.tablero.get(15));
        jTextField17.setText("");
        jTextField19.setText(String.valueOf(t.obtenerMovimientos()));

        if(!t.verificarTablero()){
            jTextField17.setText(r);
        }
        else{
            jTextField17.setText("Has ganado el juego.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);

        }
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField19;
    // End of variables declaration//GEN-END:variables
}
